Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  ExcludedMethods:
    - "class_eval"
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 20
  ExcludedMethods:
    - "included"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/**/*.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  Exclude:
    - spec/spec_helper.rb
    - "bin/**/*"
    - "ddtrace-annotation.gemspec"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"


EvalWithLocation:
  Exclude:
    - "spec/**/*.rb"
